// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mejwvqnxrqvvovopaxsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1land2cW54cnF2dm92b3BheHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDQzMDUsImV4cCI6MjA2NTgyMDMwNX0.myXC6u8eyn7Mgl1G7Bhp1k_XznZmdymStytdbP0KStk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);